config/routes.rb
Carsinfo::Application.routes.draw do

  root :to => 'cars#index'

  resources :brand_models

  resources :brands

  resources :cars

  match "cars/:id/get_models" => "cars#get_models"
  match "cars//get_models" => "cars#get_models"

end

app/models/brand.rb
class Brand
  include Mongoid::Document
  field :name, type: String

  has_many :cars
  has_many :brand_models
end

app/models/brand_model.rb
class BrandModel
  include Mongoid::Document
  belongs_to :brand

  field :name, type: String
  field :brand_id, type: String
end

app/models/car.rb
class Car
  include Mongoid::Document
  belongs_to :brand
  belongs_to :brand_model


  field :title, type: String
  field :brand_model_id, type: String
  field :brand_id, type: String
  field :year, type: Integer
  field :price, type: Float
  field :release_date, type: Date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brand_models_controller.rb
class BrandModelsController < ApplicationController
  # GET /brand_models
  # GET /brand_models.json
  def index
    @brand_models = BrandModel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brand_models }
    end
  end

  # GET /brand_models/1
  # GET /brand_models/1.json
  def show
    @brand_model = BrandModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand_model }
    end
  end

  # GET /brand_models/new
  # GET /brand_models/new.json
  def new
    @brands = Brand.all
    @brand_model = BrandModel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand_model }
    end
  end

  # GET /brand_models/1/edit
  def edit
    @brands = Brand.all
    @brand_model = BrandModel.find(params[:id])
  end

  # POST /brand_models
  # POST /brand_models.json
  def create
    @brand_model = BrandModel.new(params[:brand_model])

    respond_to do |format|
      if @brand_model.save
        format.html { redirect_to @brand_model, notice: 'Brand model was successfully created.' }
        format.json { render json: @brand_model, status: :created, location: @brand_model }
      else
        format.html { render action: "new" }
        format.json { render json: @brand_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brand_models/1
  # PUT /brand_models/1.json
  def update
    @brand_model = BrandModel.find(params[:id])

    respond_to do |format|
      if @brand_model.update_attributes(params[:brand_model])
        format.html { redirect_to @brand_model, notice: 'Brand model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brand_models/1
  # DELETE /brand_models/1.json
  def destroy
    @brand_model = BrandModel.find(params[:id])
    @brand_model.destroy

    respond_to do |format|
      format.html { redirect_to brand_models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @brands = Brand.all
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @brands = Brand.all
    @car = Car.find(params[:id])
    @brand_models = @car.brand.brand_models
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  def get_models
    brand = Brand.find(params[:brand])
    @brand_models = brand.brand_models
    render :partial => 'brand_models', :locals => { :object => @brand_models }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brand_models_helper.rb
module BrandModelsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/brand_models/_form.html.erb
<%= form_for(@brand_model) do |f| %>
  <% if @brand_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand_model.errors.count, "error") %> prohibited this brand_model from being saved:</h2>

      <ul>
      <% @brand_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br />
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brand_models/edit.html.erb
<h1>Editing brand_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand_model %> |
<%= link_to 'Back', brand_models_path %>

app/views/brand_models/index.html.erb
<h1>Listing brand_models</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brand_models.each do |brand_model| %>
  <tr>
    <td><%= brand_model.name %></td>
    <td><%= brand_model.brand.name %></td>
    <td><%= link_to 'Show', brand_model %></td>
    <td><%= link_to 'Edit', edit_brand_model_path(brand_model) %></td>
    <td><%= link_to 'Destroy', brand_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand model', new_brand_model_path %>

app/views/brand_models/new.html.erb
<h1>New brand_model</h1>

<%= render 'form' %>

<%= link_to 'Back', brand_models_path %>

app/views/brand_models/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_brand_model_path(@brand_model) %> |
<%= link_to 'Back', brand_models_path %>

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.name %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brand.name %>
</p>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/cars/_brand_models.erb
<%= label_tag :brand_model %><br />
<% unless @brand_models.blank? %>
    <%= select_tag("car[brand_model_id]", options_from_collection_for_select(@brand_models, "id", "name")) %>
<% else %>
    <%= select_tag "car[brand_model_id]","brand_model_id", :prompt => "-- Select a Model --" %>
<% end %>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :brand %><br />
    <%= select_tag("car[brand_id]", options_from_collection_for_select(@brands, "id", "name", @car.brand_id),  :prompt => "-- Select a Brand --") %>
    <div id="brand_models_div" class="field">
     <%= render :partial => 'brand_models', :locals => { :object => @brand_models } %>
    </div>
  </div>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
        <th>Title</th>
    <th>Brand Name</th>
    <th>Model</th>
    <th>Year</th>
    <th>Release Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <th><%= car.title %></th>
    <th><%= car.brand.name %></th>
    <th><%= car.brand_model.name %></th>
    <th><%= car.year %></th>
    <th><%= car.release_date %></th>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand name:</b>
  <%= @car.brand.name %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carsinfo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>